# Generated by Django 5.2.17 on 2026-10-03 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('channel', models.CharField(default='stable', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('released_at', models.DateField()),
                ('min_os', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('laravel', 'Laravel'), ('django', 'Django'), ('python', 'Python'), ('node', 'Node'), ('vue', 'Vue'), ('react', 'React'), ('php', 'Php'), ('empty', 'Empty')], default='empty', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], max_length=10)),
                ('arch', models.CharField(max_length=10)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('filename', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.release')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('default_branch', models.CharField(default='main', max_length=80)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='GitRemote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='origin', max_length=60)),
                ('url', models.CharField(max_length=500)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remotes', to='core.repository')),
            ],
        ),
        migrations.CreateModel(
            name='RunConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('command', models.CharField(max_length=500)),
                ('working_directory', models.CharField(default='${workspaceFolder}', max_length=500)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_configs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('platform', models.CharField(choices=[('win32', 'Windows'), ('darwin', 'macOS'), ('linux', 'Linux')], max_length=10)),
                ('shell_path', models.CharField(blank=True, max_length=500)),
                ('args', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=80)),
                ('base', models.CharField(choices=[('vs-dark', 'Dark'), ('vs', 'Light'), ('hc-black', 'High Contrast')], default='vs-dark', max_length=20)),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EditorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default='JetBrains Mono', max_length=120)),
                ('font_size', models.PositiveSmallIntegerField(default=14)),
                ('font_weight', models.CharField(default='400', max_length=12)),
                ('line_height', models.FloatField(default=1.5)),
                ('letter_spacing', models.FloatField(default=0)),
                ('ligatures', models.BooleanField(default=True)),
                ('smooth_rendering', models.BooleanField(default=True)),
                ('minimap', models.BooleanField(default=True)),
                ('word_wrap', models.BooleanField(default=False)),
                ('tab_size', models.PositiveSmallIntegerField(default=4)),
                ('insert_spaces', models.BooleanField(default=True)),
                ('auto_save', models.CharField(choices=[('off', 'Off'), ('afterDelay', 'After Delay'), ('onFocusChange', 'When Focus Changes'), ('onWindowChange', 'When Window Changes')], default='afterDelay', max_length=20)),
                ('auto_save_delay', models.PositiveIntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_settings', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.theme')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('telemetry_enabled', models.BooleanField(default=False)),
                ('sync_enabled', models.BooleanField(default=False, help_text='Settings/workspace sync')),
                ('ai_consent', models.BooleanField(default=False, help_text='Allow sending code to AI services')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('installed_version', models.CharField(max_length=20)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'extension')},
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('value', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
